### ISSUE TITLE
Datepicker bugs

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#1]
The React Material datepicker is a little buggy. I would consider looking at creating your own or a third party that handles dates

![image](https://user-images.githubusercontent.com/33135920/130380081-23446ddd-60ec-487c-b778-12f2d59c3ffc.png)

**Comment by r-havelka** [comment]
Here is a link to the gif I added in the discord

https://cdn.discordapp.com/attachments/754551381720825857/878769021502238790/buggy_date.gif

**Comment by anthonymorast** [comment]
Changed the date picker to one that doesn't suck.
