### ISSUE TITLE
Same stock has two different dividend data

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#11]
On the dividends page, I clicked on NVDA and thought it was cool to see it compared to the other stocks, but I noticed that NVDA was still in the list with different data. I then selected different stocks in the displayed boxes and found that the top left white box doesn't change data when you select a different stock. I see the note at the top that the stocks are limited to 5, but this is just a reminder to not forget to add that functionality in (or add it in but take the selection option from the other stocks out)

![image](https://user-images.githubusercontent.com/33135920/130388817-ad5e2df8-092c-4fdc-b7ff-81f9b344ada0.png)

**Comment by anthonymorast** [comment]
I think this happens when the screen is loading but these boxes haven't updated with the new data yet. The focused ticker (white box) is updated immediately.

I think I will cover this with a loading CircularProgress
