### ISSUE TITLE
Mismatched table header/body columns

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#15]
currently, the sector analysis portfolio builder looks like this

![image](https://user-images.githubusercontent.com/33135920/165372220-d56de8a9-87f3-4263-b440-b543273174a3.png)

and it would look a lot nicer if the columns were aligned

![image](https://user-images.githubusercontent.com/33135920/165372312-1774c54d-022d-4268-9437-2fcf09176230.png)

**Comment by anthonymorast** [comment]
Fixed this on all pages with a BootstrapTable component.
