### ISSUE TITLE
better blog url links

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#16]
I get that you want that sweet, sweet income from medium and any affiliated links you have in your articles, but technical references should be at the bottom of the page, not under the title.

![image](https://user-images.githubusercontent.com/33135920/165372734-f57674ea-694f-4ff2-8906-5b5efaae9fe9.png)

I also changed the name to see how it looked. I don't know if "1, 2" is better than spelling out part of the article title

![image](https://user-images.githubusercontent.com/33135920/165374634-748864f3-0a4c-436f-aae3-6ea6a77ce24b.png)

**Comment by r-havelka** [comment]
Maybe `Blog 1, Blog 2` or `Blog1, Blog2` would look better

![image](https://user-images.githubusercontent.com/33135920/165374990-b0996dc2-8b03-48cc-9831-97a65b13e546.png)

**Comment by anthonymorast** [comment]
Kept them where they are but added some words
