### ISSUE TITLE
Graph displays incorrectly

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#4]
Analyzing the ROE and P/E for 3 companies (AAPL, AMZN, and INTC) on the Line Item Plots page. That gave a graph that had Q1 2020 out of place.

![image](https://user-images.githubusercontent.com/33135920/130382292-972f06d1-c1c8-4b65-9507-46a2bb4beb63.png)

**Comment by anthonymorast** [comment]
Fixed this by using calendar rather than fiscal quarters.
