### ISSUE TITLE
Charts have more decimals than is needed

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/ntrinsic_bugs#8]
These are both on the Historical Price Charts

When I have Raw Data selected, I see a rounding error on AMZN's decimals. It is either something like 12.349997 or 12.340004
![image](https://user-images.githubusercontent.com/33135920/130386135-f0dd6533-530b-4d16-b550-bd49bb43e720.png)

When I have Normalized Data selected, I see more decimals than is interesting
![image](https://user-images.githubusercontent.com/33135920/130385858-865931a4-4764-41cd-b75a-c3d2fed4a0ff.png)

**Comment by anthonymorast** [comment]
Rounding to two decimal places for raw and normalized data.
